ActiveSupport::Inflector.inflections(:en) do |inflect|

	#SINGULARES MODULO SGI (SISTEMA DE GESTION INTEGRAL)
	inflect.singular "atributo", "atributos"
	inflect.singular "componente", "componentes"
	inflect.singular "menu", "menus"
	inflect.singular "user", "users"
	inflect.singular "rol", "roles"
	inflect.singular "opcion", "opciones"
	inflect.singular "opcion_ca", "opcion_cas"
	inflect.singular "rol_opcion_ca", "rol_opcion_cas"
	inflect.singular "rol_user", "rol_users"
	inflect.singular "usuario_proceso_permiso", "usuario_proceso_permisos"
	
	inflect.singular "empresa", "empresas"
	inflect.singular "etapa_documento", "etapa_documentos"
	inflect.singular "etapa_solicitud", "etapa_solicitudes"
	inflect.singular "tipo_documento", "tipo_documentos"
	inflect.singular "tipo_proceso", "tipo_procesos"
	inflect.singular "tipo_sistema", "tipo_sistemas"
	inflect.singular "tipo_usuario", "tipo_usuarios"
	inflect.singular "macro_proceso", "macro_procesos"
	inflect.singular "persona", "personas"
	inflect.singular "estado_documento", "estado_documentos"
	inflect.singular "proceso", "procesos"
	inflect.singular "sub_proceso", "sub_procesos"
	inflect.singular "usuario_proceso", "usuario_procesos"
	inflect.singular "documento", "documentos"
	inflect.singular "historial_documento", "historial_documentos"
	inflect.singular "solicitud_cambio", "solicitud_de_cambios"
	inflect.singular "seguimiento_solicitud", "seguimiento_solicitudes"
	inflect.singular "comentario", "comentarios"

	#PLURALES MODULO SGI (SISTEMA DE GESTION INTEGRAL)
	inflect.plural "atributo", "atributos"
	inflect.plural "componente", "componentes"
	inflect.plural "menu", "menus"
	inflect.plural "user", "users"
	inflect.plural "rol", "roles"
	inflect.plural "opcion", "opciones"
	inflect.plural "opcion_ca", "opcion_cas"
	inflect.plural "rol_opcion_ca", "rol_opcion_cas"
	inflect.plural "rol_user", "rol_users"
	inflect.plural "usuario_proceso_permiso", "usuario_proceso_permisos"
	
	inflect.plural "empresa", "empresas"
	inflect.plural "etapa_documento", "etapa_documentos"
	inflect.plural "etapa_solicitud", "etapa_solicitudes"
	inflect.plural "tipo_documento", "tipo_documentos"
	inflect.plural "tipo_proceso", "tipo_procesos"
	inflect.plural "tipo_sistema", "tipo_sistemas"
	inflect.plural "tipo_usuario", "tipo_usuarios"
	inflect.plural "macro_proceso", "macro_procesos"
	inflect.plural "persona", "personas"
	inflect.plural "estado_documento", "estado_documentos"
	inflect.plural "proceso", "procesos"
	inflect.plural "sub_proceso", "sub_procesos"
	inflect.plural "usuario_proceso", "usuario_procesos"
	inflect.plural "documento", "documentos"
	inflect.plural "historial_documento", "historial_documentos"
	inflect.plural "solicitud_cambio", "solicitud_de_cambios"
	inflect.plural "seguimiento_solicitud", "seguimiento_solicitudes"
	inflect.plural "comentario", "comentarios"

	#IRREGULARES MODULO SGI (SISTEMA DE GESTION INTEGRAL)
	inflect.irregular "atributo", "atributos"
	inflect.irregular "componente", "componentes"
	inflect.irregular "menu", "menus"
	inflect.irregular "user", "users"
	inflect.irregular "rol", "roles"
	inflect.irregular "opcion", "opciones"
	inflect.irregular "opcion_ca", "opcion_cas"
	inflect.irregular "rol_opcion_ca", "rol_opcion_cas"
	inflect.irregular "rol_user", "rol_users"
	inflect.irregular "usuario_proceso_permiso", "usuario_proceso_permisos"
	
	inflect.irregular "empresa", "empresas"
	inflect.irregular "etapa_documento", "etapa_documentos"
	inflect.irregular "etapa_solicitud", "etapa_solicitudes"
	inflect.irregular "tipo_documento", "tipo_documentos"
	inflect.irregular "tipo_proceso", "tipo_procesos"
	inflect.irregular "tipo_sistema", "tipo_sistemas"
	inflect.irregular "tipo_usuario", "tipo_usuarios"
	inflect.irregular "macro_proceso", "macro_procesos"
	inflect.irregular "persona", "personas"
	inflect.irregular "estado_documento", "estado_documentos"
	inflect.irregular "proceso", "procesos"
	inflect.irregular "sub_proceso", "sub_procesos"
	inflect.irregular "usuario_proceso", "usuario_procesos"
	inflect.irregular "documento", "documentos"
	inflect.irregular "historial_documento", "historial_documentos"
	inflect.irregular "solicitud_cambio", "solicitud_de_cambios"
	inflect.irregular "seguimiento_solicitud", "seguimiento_solicitudes"
	inflect.irregular "comentario", "comentarios"

end